server:
  port: 8081 #puerto del servicio
spring:
  cloud:
    config:
      server:
        git:
          #rama o branch en que se va a trabajar
          default-label: config-server
          #uri del repositiorio
          uri: https://github.com/axl-bit/MicroServicios-Ejercicio
          search-paths: config-data
  application:
    #nombre del proyecto
    name: config-servicio